security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }

        chain_provider:
            chain:
                providers: [ app_student_provider, app_teacher_provider ]
        app_student_provider:
            entity:
                class: App\Entity\Student
                property: username
        app_teacher_provider:
            entity:
                class: App\Entity\Teacher
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_STUDENT: [ROLE_USER, ROLE_STUDENT]
        ROLE_TEACHER: [ROLE_USER, ROLE_TEACHER]
        ROLE_ADMIN: [ROLE_TEACHER,ROLE_STUDENT,ROLE_ADMIN]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    encoders:
        App\Entity\User:
            algorithm: auto